import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    paddingHorizontal: 14,
    paddingBottom: 16,
  },
  bg: { flex: 1 },
  bgImage: { opacity: 0.65 },
  bgOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.2)",
  },
  topBar: {
    paddingHorizontal: 4,
    paddingTop: 8,
    paddingBottom: 14,
    alignItems: "center",
    gap: 6,
  },
  topTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "#f8f3eb",
    margin: 10,
  },
  topLogo: {
    width: 140,
    height: 46,
    resizeMode: "contain",
  },
  emptyState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#fdf8f0",
    textAlign: "center",
  },
  emptySubtitle: {
    marginTop: 6,
    color: "#f1e6d5",
    textAlign: "center",
  },
  listContent: {
    paddingBottom: 32,
    gap: 12,
  },
  card: {
    flexDirection: "row",
    gap: 12,
    backgroundColor: "#fbf7f0",
    borderRadius: 18,
    padding: 12,
    borderWidth: 1,
    borderColor: "#e6d7c7",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  productImg: {
    width: 72,
    height: 72,
    borderRadius: 12,
    backgroundColor: "#e8e0d6",
  },
  cardBody: { flex: 1, gap: 6 },
  cardHeaderRow: { flexDirection: "row", justifyContent: "space-between", gap: 8 },
  cardTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: "800",
    color: "#2c1b12",
  },
  cardCategory: {
    color: "#7a6858",
  },
  itemPrice: {
    fontWeight: "800",
    color: "#a43b36",
  },
  qtyRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  qtyControl: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f1e7db",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#ddcbb9",
  },
  qtyBtn: {
    width: 38,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  qtyBtnText: { fontSize: 18, fontWeight: "800", color: "#654332" },
  qtyValueBox: {
    minWidth: 36,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  qtyText: { fontSize: 16, fontWeight: "800", color: "#2c1b12" },
  removeLink: { paddingHorizontal: 6, paddingVertical: 4 },
  removeLinkText: { color: "#a43b36", fontWeight: "700" },
  summaryCard: {
    marginTop: 16,
    backgroundColor: "#fbf7f0",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e6d7c7",
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
    gap: 14,
  },
  totalRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  totalLabel: { fontSize: 16, fontWeight: "800", color: "#2c1b12" },
  totalValue: { fontSize: 20, fontWeight: "900", color: "#a43b36" },
  clearLink: { color: "#a43b36", fontWeight: "700", textDecorationLine: "underline" },
  checkoutBtn: {
    backgroundColor: "#b13c38",
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  checkoutText: { color: "#fff", fontWeight: "800", fontSize: 16, letterSpacing: 0.4 },
});
